import { keyframes } from 'styled-components'

/* ----------------------------------------------
 * Generated by Animista on 2023-1-23 17:45:6
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

export const blink = keyframes` {
  0%,
  50%,
  100% {
    opacity: 1;
  }
  25%,
  75% {
    opacity: 0;
  }
}`

export const slideLeft = keyframes`{
  0% {
    transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    transform: translateX(0);
    opacity: 1;
  }
}
`

export const fadeIn = keyframes`{
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}`

export const slideRight = keyframes`{
  0% {
    transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    transform: translateX(0);
    opacity: 1;
  }
}
`
